In [ ]:
# 1) Imports
import json
import pandas as pd
from pathlib import Path

In [2]:
# DATASET INFO_LOTES

In [3]:
# 2) Ruta
ruta = Path("..") / "dataset" / "info_lote.json"

# Verificación
print("Existe archivo?:", ruta.exists(), "| Ruta:", ruta)

# 3) Leer el JSON
with open(ruta, "r", encoding="utf-8") as f:
    data = json.load(f)

print("Tipo dato:", type(data))

rows = []
for lote, lista in data.items():
    for item in lista:
        item["lote"] = lote  # añadimos la clave como nueva columna
        rows.append(item)


df_info_lotes = pd.DataFrame(rows)
df_info_lotes.head(1)

Existe archivo?: False | Ruta: ../dataset/info_lote.json

FileNotFoundError: [Errno 2] No such file or directory: '../dataset/info_lote.json'

In [ ]:
# DATASET LOTES

In [ ]:
# 2) Ruta
ruta_2 = Path("..") / "dataset" / "lotes.json"

# Verificación
print("Existe archivo?:", ruta_2.exists(), "| Ruta:", ruta_2)

# 3) Leer el JSON
with open(ruta_2, "r", encoding="utf-8") as f:
    data_2 = json.load(f)

print("Tipo dato:", type(data_2))

df_lotes= pd.DataFrame(list(data_2.items()), columns=["t_id", "lote"])
df_lotes.head(1)

Existe archivo?: True | Ruta: ..\dataset\lotes.json
Tipo dato: <class 'dict'>

          t_id             lote
0  Apple 1.png  G80V76K49J80T71

In [ ]:
# DATASET PROVEEDORES

In [ ]:
# 2) Ruta
ruta_3 = Path("..") / "dataset" / "proveedores.json"

# Verificación
print("Existe archivo?:", ruta_3.exists(), "| Ruta:", ruta_3)

# 3) Leer el JSON
with open(ruta_3, "r", encoding="utf-8") as f:
    data_3 = json.load(f)

print("Tipo dato:", type(data_3))

# Creamos una lista con las columnas que necesitamos en el DF
rows_3 = []
for proveedor, lista in data_3.items():
    for item in lista:
        item["proveedor"] = proveedor  # añadimos la clave como nueva columna
        rows_3.append(item)


df_proveedores = pd.DataFrame(rows_3)
df_proveedores.head(1)

Existe archivo?: True | Ruta: ..\dataset\proveedores.json
Tipo dato: <class 'dict'>

          t_id                             proveedor
0  Apple 1.png  Agricultura Inteligente TechCultivos

In [ ]:
# DATASET PROVEEDORES-CLIENTES

In [ ]:
# 2) Ruta
ruta_4 = Path("..") / "dataset" / "proveedores-clientes.json"

# Verificación
print("Existe archivo?:", ruta_4.exists(), "| Ruta:", ruta_4)

# 3) Leer el JSON
with open(ruta_4, "r", encoding="utf-8") as f:
    data_4 = json.load(f)

print("Tipo dato:", type(data_4))

# Creamos una lista para los nombres de las columnas del DF
rows_4 = []

for proveedor, lista in data_4.items():
    for item in lista:
        # item = ["image12.png", "CompraMaestra"] ejemplo de lógica al indexar
        t_id = item[0] if len(item) > 0 else None
        cliente = item[1] if len(item) > 1 else None

        rows_4.append({
            "proveedor": proveedor,
            "t_id": t_id,
            "cliente": cliente
        })


df_proveedores_clientes = pd.DataFrame(rows_4)
df_proveedores_clientes.head(1)

Existe archivo?: True | Ruta: ..\dataset\proveedores-clientes.json
Tipo dato: <class 'dict'>

                              proveedor         t_id        cliente
0  Agricultura Inteligente TechCultivos  Apple 1.png  CompraMaestra

In [ ]:
# DATASET TIPO

In [ ]:
# 2) Ruta
ruta_5 = Path("..") / "dataset" / "tipo.json"

# Verificación
print("Existe archivo?:", ruta_5.exists(), "| Ruta:", ruta_5)

# 3) Leer el JSON
with open(ruta_5, "r", encoding="utf-8") as f:
    data_5 = json.load(f)

print("Tipo dato:", type(data_5))

# Creamos una lista con las columnas que necesitamos en el DF
rows_5 = []
for tipo, lista in data_5.items():
    for item in lista:
        item["tipo"] = tipo  # añadimos la clave como nueva columna
        rows_5.append(item)


df_tipo = pd.DataFrame(rows_5)
df_tipo.head(1)

Existe archivo?: True | Ruta: ..\dataset\tipo.json
Tipo dato: <class 'dict'>

          t_id   tipo  tiempo_recogida
0  Apple 1.png  Apple              433

In [ ]:
# DATASET VENTA EN CLIENTE

In [ ]:
# 2) Ruta
ruta_6 = Path("..") / "dataset" / "venta_en_cliente.json"

# Verificación
print("Existe archivo?:", ruta_6.exists(), "| Ruta:", ruta_6)

# 3) Leer el JSON
with open(ruta_6, "r", encoding="utf-8") as f:
    data_6 = json.load(f)

print("Tipo dato:", type(data_6))

# Creamos una lista con las columnas para el DF
rows_6 = []
for cliente, lista in data_6.items():
    for item in lista:
        item["cliente"] = cliente  # añadimos la clave como nueva columna
        rows_6.append(item)


df_venta_en_cliente = pd.DataFrame(rows_6)
df_venta_en_cliente.head(1)

Existe archivo?: True | Ruta: ..\dataset\venta_en_cliente.json
Tipo dato: <class 'dict'>

          t_id  tiempo_venta  precio_venta        peso        cliente
0  Apple 1.png         437.0       4.90968  264.195357  CompraMaestra

TABLAS MAESTRAS

In [ ]:
# FRUTAS

frutas = df_tipo[['tipo']].drop_duplicates().reset_index(drop=True)
frutas['id_tipo'] = frutas.index + 1
frutas = frutas[['id_tipo', 'tipo']]
frutas

    id_tipo         tipo
0         1        Apple
1         2       Banana
2         3    Carambola
3         4        Guava
4         5         Kiwi
5         6        Mango
6         7    muskmelon
7         8       Orange
8         9        Peach
9        10         Pear
10       11    Persimmon
11       12       Pitaya
12       13         Plum
13       14  Pomegranate
14       15     Tomatoes

In [ ]:
# MARCA

marca = df_info_lotes[['marca']].drop_duplicates().reset_index(drop=True)
marca['id_marca'] = marca.index + 1
marca = marca[['id_marca', 'marca']]
marca

In [ ]:
# PROVEEDORES

proveedores = df_proveedores_clientes[['proveedor']].drop_duplicates().reset_index(drop=True)
proveedores['id_proveedor'] = proveedores.index + 1
proveedores = proveedores[['id_proveedor', 'proveedor']]
proveedores

    id_proveedor                             proveedor
0              1  Agricultura Inteligente TechCultivos
1              2           Semillero Genético BioCampo
2              3            Pesca Sustentable Oceanica
3              4          Carnes Sostenibles CampoReal
4              5           Silos y Almacenes AgroVault
5              6                 Veterinaria EcoAnimal
6              7             Agronutrientes del Futuro
7              8                   BioCosecha Orgánica
8              9              Pecuaria Moderna Alcaraz
9             10                      Avícola San José
10            11     Fertilizantes Naturales del Valle
11            12   Herramientas Agroindustriales Gómez
12            13               AgroEnvases Sostenibles
13            14               AgroSoftware Soluciones
14            15             Semillas Innovadoras S.A.
15            16       Ganadería Orgánica TierraFértil
16            17       Cultivos Hidropónicos Innovagro
17            18    AgroQuímicos Naturales BioCultivos
18            19                 EcoFungicidas Morales
19            20                 RiegoSmart Innovación
20            21             Energía Renovable AgroSol
21            22              Tecnosembradoras del Sur
22            23                       Apícola EcoMiel
23            24         Insecticidas Ecológicos Reyes
24            25            Productos Lácteos EcoLeche
25            26              Agrícola Solaris Energía
26            27                Vivero Verde Esperanza
27            28           Cosechadoras Progresivas SA
28            29          Maquinaria Agrícola Avanzada
29            30             AgroSuministros del Campo
30            31          Tractores Eficientes Delgado
31            32          Mallas AgroProtección García
32            33                   EcoRiego Soluciones
33            34     Reforestación Ecológica VerdeVida
34            35                 Fitosanitarios BioPro

In [ ]:
# CLIENTES

clientes = df_proveedores_clientes[['cliente']].drop_duplicates().reset_index(drop=True)
clientes['id_cliente'] = clientes.index + 1
clientes = clientes[['id_cliente', 'cliente']]
clientes

    id_cliente                     cliente
0            1               CompraMaestra
1            2            Almacén Estrella
2            3       EcoMercado Sostenible
3            4              Cosecha Fresca
4            5  Central de Abastos Central
5            6       El Bazar de la Comida
6            7          Alimentación Total
7            8          Distribuidora Alfa
8            9             La Gran Cosecha
9           10                   EcoTienda
10          11          Mercado Fresco XYZ
11          12           Alimentos Premium
12          13          Mercado del Barrio
13          14          Delicias del Campo
14          15             Tienda Familiar
15          16      Distribuidora Nacional
16          17      Distribuciones del Sol
17          18                  MegaCompra
18          19            SuperValle Verde
19          20                  MegaAhorro
20          21     Supermercados del Valle
21          22          SuperMercado Ideal
22          23           SuperOfertas Plus
23          24              Tienda Selecta
24          25            La Canasta Feliz
25          26              MaxiDescuentos
26          27               MaxiAlimentos
27          28                CompraRápida
28          29            Comercial Fresco
29          30       Distribuidora Gourmet
30          31             La Tienda Justa
31          32           La Ruta del Sabor
32          33         SuperAhorro Express
33          34              SuperEconómico

TABLAS DINÁMICAS

In [ ]:
# LOTES

lotes = df_lotes[['lote', 't_id']].drop_duplicates().reset_index(drop=True)
lotes['id_lote'] = lotes.index + 1
lotes = lotes[['id_lote', 'lote', 't_id']]
lotes

MERGE ENTRE DF_INFO_LOTES Y TABLA MARCA

In [ ]:
# Creamos estas lineas de código para hacerlo más robusto. Es decir, en caso de ejecutar más de una vez el merge, hacemos una limpieza inicial para evitar
# duplicados de la variable id_marca y asi no entra en error.
evitar_conflicto = [c for c in df_info_lotes.columns if c.startswith('id_marca')] # con list comprehension filtramos en las columnas que empiezan por id_marca
df_info_lotes = df_info_lotes.drop(columns=evitar_conflicto, errors='ignore')     # Machacamos el df_info_lotes indicando la eliminación de las columnas del df anterior
                                                                                  # mediante errors para igonarar si alguna columna no existe

# merge limpio
df_info_lotes = df_info_lotes.merge(
    marca[['id_marca', 'marca']],
    on='marca',
    how='left',
    validate='many_to_one'  # comprobar que no haya duplicados en la tabla de la derecha
)

df_info_lotes

NUEVO DF DE INFO_LOTES DONDE ME QUEDO CON LOS VALORES UNICOS DE t_id Y id_marca

In [ ]:
df_info_lotes_unique = (
    df_info_lotes[['t_id', 'id_marca']].drop_duplicates(subset=['t_id'])
)
df_info_lotes_unique['t_id'].duplicated().sum()
df_info_lotes_unique

MERGE ENTRE DF LOTES Y EL NUEVO DF_INFO_LOTES_UNIQUE

In [ ]:
evitar_conflicto_2 = [c for c in lotes.columns if c.startswith('id_marca')]
lotes = lotes.drop(columns=evitar_conflicto_2, errors='ignore')

lotes = lotes.merge(
    df_info_lotes_unique,
    on='t_id',
    how='left',
    validate='many_to_one'
)

lotes

MERGE ENTRE DF_TIPO Y  TABLAS FRUTAS

In [ ]:
evitar_conflicto_3 = [c for c in df_tipo.columns if c.startswith('id_tipo')]
df_tipo = df_tipo.drop(columns=evitar_conflicto_3, errors='ignore')

df_tipo = df_tipo.merge(
    frutas[['id_tipo', 'tipo']],
    on='tipo',
    how='left',
    validate='many_to_one'
)

df_tipo

VALORES UNICOS DE DF_TIPO EN LAS VARIABLES t_id Y id_tipo

In [ ]:
df_tipo_unique = (
    df_tipo[['t_id', 'id_tipo']].drop_duplicates(subset=['t_id'])
)
df_tipo_unique['t_id'].duplicated().sum()
df_tipo_unique

MERGE ENTRE  LOTES Y DF_TIPO_UNIQUE

In [ ]:
evitar_conflicto_4 = [c for c in lotes.columns if c.startswith('id_tipo')]
lotes = lotes.drop(columns=evitar_conflicto_4, errors='ignore')

lotes = lotes.merge(
    df_tipo_unique,
    on='t_id',
    how='left',
    validate='many_to_one'
)

lotes

,id_lote,lote,t_id,id_marca,id_tipo
0,1,G80V76K49J80T71,Apple 1.png,1,1
1,2,G80V76K49L46V78M,Apple 10.png,2,1
2,3,G80V76K49L48J80T71,Apple 100.png,3,1
3,4,G80V76K49L49J80T71,Apple 101.png,4,1
4,5,G80V76K49L50J80T71,Apple 102.png,5,1
...,...,...,...,...,...
69682,69683,D65S79D79K83L48U57Q46V78M,Tamotoes00995.png,24,15
69683,69684,D65S79D79K83L48U57R46V78M,Tamotoes00996.png,21,15
69684,69685,D65S79D79K83L48U57S46V78M,Tamotoes00997.png,24,15
69685,69686,D65S79D79K83L48U57T46V78M,Tamotoes00998.png,13,15
69686,69687,D65S79D79K83L48U57U46V78M,Tamotoes00999.png,29,15

In [ ]:
# COMPRAS

In [ ]:
compras = df_tipo[['tiempo_recogida', 't_id']].reset_index(drop=True)
compras['id_compra'] = compras.index + 1
compras = compras[['id_compra', 'tiempo_recogida', 't_id']]
compras

VALORES UNICOS DE VARIABLES

In [ ]:
df_info_lotes_unique_2 = (
    df_info_lotes[['t_id', 'coste_inicial']].drop_duplicates(subset=['t_id'])
)
df_info_lotes_unique_2['t_id'].duplicated().sum()
df_info_lotes_unique_2

                    t_id  coste_inicial
0            Apple 1.png       2.642048
1           Apple 10.png       1.702296
2          Apple 100.png       1.176703
3          Apple 101.png       2.314693
4          Apple 102.png       2.473541
...                  ...            ...
70544  Tamotoes00995.png       2.477602
70545  Tamotoes00996.png       2.094206
70546  Tamotoes00997.png       2.332970
70547  Tamotoes00998.png       2.325945
70548  Tamotoes00999.png       2.124180

[69687 rows x 2 columns]

In [ ]:
#MERGE ENTRE  COMPRAS Y DF_INFO_LOTES

In [ ]:
evitar_conflicto_5 = [c for c in compras.columns if c.startswith('coste_inicial')]
compras = compras.drop(columns=evitar_conflicto_5, errors='ignore')

compras = compras.merge(
    df_info_lotes_unique_2,
    on='t_id',
    how='left',
    validate='many_to_one'
)

compras

In [ ]:
#MERGE ENTRE DF_PROVEEDORES_CLIENTES  Y  TABLA PROVEEDORES

In [ ]:
evitar_conflicto_6 = [c for c in df_proveedores_clientes.columns if c.startswith('id_proveedor')]
df_proveedores_clientes = df_proveedores_clientes.drop(columns=evitar_conflicto_6, errors='ignore')

df_proveedores_clientes = df_proveedores_clientes.merge(
    proveedores[['id_proveedor', 'proveedor']],
    on='proveedor',
    how='left',
    validate='many_to_one'
)

df_proveedores_clientes

,proveedor,t_id,cliente,id_proveedor
0,Agricultura Inteligente TechCultivos,Apple 1.png,CompraMaestra,1
1,Agricultura Inteligente TechCultivos,Apple 109.png,Almacén Estrella,1
2,Agricultura Inteligente TechCultivos,Apple 205.png,EcoMercado Sostenible,1
3,Agricultura Inteligente TechCultivos,Apple 240.png,Cosecha Fresca,1
4,Agricultura Inteligente TechCultivos,Apple 25.png,Central de Abastos Central,1
...,...,...,...,...
70544,Fitosanitarios BioPro,Tamotoes00759.png,Almacén Estrella,35
70545,Fitosanitarios BioPro,Tamotoes00772.png,SuperValle Verde,35
70546,Fitosanitarios BioPro,Tamotoes00804.png,El Bazar de la Comida,35
70547,Fitosanitarios BioPro,Tamotoes00807.png,El Bazar de la Comida,35
70548,Fitosanitarios BioPro,Tamotoes00985.png,Supermercados del Valle,35

VALORES UNICOS DEL DF_PROVEEDORES_CLIENTES EN LAS VARIABLES t_id Y proveedor

In [ ]:
df_proveedores_clientes_unique = (
    df_proveedores_clientes[['t_id', 'id_proveedor']].drop_duplicates(subset=['t_id'])
)
df_proveedores_clientes_unique['t_id'].duplicated().sum()
df_proveedores_clientes_unique

                    t_id  id_proveedor
0            Apple 1.png             1
1          Apple 109.png             1
2          Apple 205.png             1
3          Apple 240.png             1
4           Apple 25.png             1
...                  ...           ...
70544  Tamotoes00759.png            35
70545  Tamotoes00772.png            35
70546  Tamotoes00804.png            35
70547  Tamotoes00807.png            35
70548  Tamotoes00985.png            35

[69687 rows x 2 columns]

In [ ]:
#MERGE ENTRE TABLA COMPRAS Y DF_PROVEEDORES_CLIENTES_UNIQUE

In [ ]:
evitar_conflicto_8 = [c for c in compras.columns if c.startswith('id_proveedor')]
compras = compras.drop(columns=evitar_conflicto_8, errors='ignore')

compras  = compras.merge(
    df_proveedores_clientes_unique,
    on='t_id',
    how='left',
    validate='many_to_one'
)

compras

,id_compra,tiempo_recogida,t_id,coste_inicial,id_proveedor
0,1,433,Apple 1.png,2.642048,1
1,2,252,Apple 10.png,1.702296,2
2,3,442,Apple 100.png,1.176703,3
3,4,647,Apple 101.png,2.314693,4
4,5,418,Apple 102.png,2.473541,5
...,...,...,...,...,...
70544,70545,614,Tamotoes00995.png,2.477602,2
70545,70546,433,Tamotoes00996.png,2.094206,29
70546,70547,432,Tamotoes00997.png,2.332970,34
70547,70548,497,Tamotoes00998.png,2.325945,16
70548,70549,10,Tamotoes00999.png,2.124180,30

In [ ]:
#filtro para probar

df_proveedores_clientes[df_proveedores_clientes["t_id"] == "Tamotoes00995.png"]

,proveedor,t_id,cliente,id_proveedor
4038,Semillero Genético BioCampo,Tamotoes00995.png,SuperOfertas Plus,2

MERGE ENTRE TABLA COMPRAS Y TABLA LOTES

In [ ]:
evitar_conflicto_9 = [c for c in compras.columns if c.startswith('id_lote')]
compras = compras.drop(columns=evitar_conflicto_9, errors='ignore')

compras  = compras.merge(
  lotes[['id_lote', 't_id']],
    on='t_id',
    how='left',
    validate='many_to_one'
)

compras.sample(5)

,id_compra,tiempo_recogida,t_id,coste_inicial,id_proveedor,id_lote
56172,56173,39,Peach00859.png,2.862555,10,55311
23637,23638,592,GuavaÒÇé1346.png,1.949159,26,22776
2503,2504,588,Apple De03881.png,1.810726,24,2465
46562,46563,222,Mango002896.png,1.920178,20,45701
64703,64704,406,PlumÒÇé171.png,1.892001,5,63842

In [ ]:
compras = compras.drop(columns=['t_id'])
compras

       id_compra  tiempo_recogida  coste_inicial  id_proveedor  id_lote
0              1              433       2.642048             1        1
1              2              252       1.702296             2        2
2              3              442       1.176703             3        3
3              4              647       2.314693             4        4
4              5              418       2.473541             5        5
...          ...              ...            ...           ...      ...
70544      70545              614       2.477602             2    69683
70545      70546              433       2.094206            29    69684
70546      70547              432       2.332970            34    69685
70547      70548              497       2.325945            16    69686
70548      70549               10       2.124180            30    69687

[70549 rows x 5 columns]

In [ ]:
# VENTAS

MERGE ENTRE DF_VENTA_EN_CLIENTE Y TABLA CLIENTES

In [ ]:
evitar_conflicto_10 = [c for c in df_venta_en_cliente.columns if c.startswith('id_cliente')]
df_venta_en_cliente = df_venta_en_cliente.drop(columns=evitar_conflicto_10, errors='ignore')

df_venta_en_cliente = df_venta_en_cliente.merge(
    clientes,
    on='cliente',
    how='left',
    validate='many_to_one'
)

df_venta_en_cliente

CREAMOS LA TABLAS VENTAS, PREVIAMENTE HICIMOS  MERGE ENTRE DF_VENTA_EN_CLIENTE Y TABLAS CLIENTES PARA OBTENER id_cliente

In [ ]:
ventas = df_venta_en_cliente[['t_id', 'tiempo_venta', 'precio_venta', 'peso', 'id_cliente']].reset_index(drop=True)
ventas['id_venta'] = ventas.index + 1
ventas = ventas[['id_venta', 't_id', 'tiempo_venta', 'precio_venta', 'peso', 'id_cliente']]
ventas

MERGE ENTRE TABLA VENTAS Y TABLA LOTES

In [ ]:
evitar_conflicto_11 = [c for c in ventas.columns if c.startswith('id_lote')]
ventas = ventas.drop(columns=evitar_conflicto_11, errors='ignore')

ventas  = ventas.merge(
  lotes[['id_lote', 't_id']],
    on='t_id',
    how='left',
    validate='many_to_one'
)

ventas

,id_venta,t_id,tiempo_venta,precio_venta,peso,id_cliente,id_lote
0,1,Apple 1.png,437.0,4.909680,264.195357,1,1
1,2,Apple 10.png,259.0,3.425103,141.647327,1,2
2,3,Apple 135.png,388.0,3.468746,516.167670,1,41
3,4,Apple 218.png,484.0,4.345632,267.665780,1,133
4,5,Apple 304.png,638.0,3.709716,326.369599,1,229
...,...,...,...,...,...,...,...
70544,70545,Tamotoes00677.png,423.0,4.207169,452.063145,4,69330
70545,70546,Tamotoes00730.png,620.0,4.639173,161.608887,4,69390
70546,70547,Tamotoes00765.png,333.0,2.359417,229.885578,4,69428
70547,70548,Tamotoes00815.png,526.0,3.176057,390.352480,4,69484
70548,70549,Tamotoes00824.png,40.0,3.650941,451.698684,4,69494

In [ ]:
ventas = ventas.drop(columns=['t_id'])
ventas

       id_venta  tiempo_venta  precio_venta        peso  id_cliente  id_lote
0             1         437.0      4.909680  264.195357           1        1
1             2         259.0      3.425103  141.647327           1        2
2             3         388.0      3.468746  516.167670           1       41
3             4         484.0      4.345632  267.665780           1      133
4             5         638.0      3.709716  326.369599           1      229
...         ...           ...           ...         ...         ...      ...
70544     70545         423.0      4.207169  452.063145           4    69330
70545     70546         620.0      4.639173  161.608887           4    69390
70546     70547         333.0      2.359417  229.885578           4    69428
70547     70548         526.0      3.176057  390.352480           4    69484
70548     70549          40.0      3.650941  451.698684           4    69494

[70549 rows x 6 columns]

------------------------------------------------- --------TABLAS DEFINITIVAS ------------------------------------------------------------------------------

In [ ]:
frutas.head(1)

   id_tipo   tipo
0        1  Apple

In [ ]:
marca.head(1)

   id_marca          marca
0         1  ParaísoFrutal

In [ ]:
proveedores.head(1)

   id_proveedor                             proveedor
0             1  Agricultura Inteligente TechCultivos

In [ ]:
clientes.head(1)

   id_cliente        cliente
0           1  CompraMaestra

In [ ]:
lotes.head(1)

   id_lote             lote         t_id  id_marca  id_tipo
0        1  G80V76K49J80T71  Apple 1.png         1        1

In [ ]:
compras.head(1)

   id_compra  tiempo_recogida  coste_inicial  id_proveedor  id_lote
0          1              433       2.642048             1        1

In [ ]:
ventas.head(1)

   id_venta  tiempo_venta  precio_venta        peso  id_cliente  id_lote
0         1         437.0       4.90968  264.195357           1        1