# Notebook para creación del datase
En este notebook se registra lo que se ha hecho para obtener el dataset de los paths y los archivos para hacer el procesado de muestras por ML pm

In [1]:
import pandas as pd
import numpy as np

In [3]:
pwd

'/Users/fcofraguas/Desktop/Master Pontia/Master Pontia/Visión artificial/archive'

## Preprocesamiento
En la carpeta donde estaban las imagenes se han generado dos archivos, uno con todos los documentos y otro sólo con las carpetas. Los archivos se obtenian con estos comandos

find . -type f > file_path
find . -type d > folder_path

Y a partir de aqui, se ha creado un archivo extrayendo del file_path el folder_path

grep -vxFf folder_path file_path > solo_archivos.txt

El proceso va a ser cargar un archivo que tiene la lista de los paths de las imagenes, y generar un dataset con pathb y frutas

In [2]:
#nombre_columnas=["path"]
df_raw = pd.read_csv("solo_archivos.txt", header=None)
#df_raw.column=nombre_columnas
df_raw

                                     0
0       Apple/Apple E/Apple E08152.png
1         Apple/Apple E/Apple E117.png
2         Apple/Apple E/Apple E103.png
3      Apple/Apple E/Apple Ee01601.png
4       Apple/Apple E/Apple E05112.png
...                                ...
70546       Tomatoes/Tamotoes00485.png
70547      Tomatoes/Tamotoes001605.png
70548      Tomatoes/Tamotoes001611.png
70549      Tomatoes/Tamotoes001177.png
70550       Tomatoes/Tamotoes00491.png

[70551 rows x 1 columns]

In [3]:
df_raw["fruta"]=df_raw[0].str.split("/").str[0]
df_raw

                                     0     fruta
0       Apple/Apple E/Apple E08152.png     Apple
1         Apple/Apple E/Apple E117.png     Apple
2         Apple/Apple E/Apple E103.png     Apple
3      Apple/Apple E/Apple Ee01601.png     Apple
4       Apple/Apple E/Apple E05112.png     Apple
...                                ...       ...
70546       Tomatoes/Tamotoes00485.png  Tomatoes
70547      Tomatoes/Tamotoes001605.png  Tomatoes
70548      Tomatoes/Tamotoes001611.png  Tomatoes
70549      Tomatoes/Tamotoes001177.png  Tomatoes
70550       Tomatoes/Tamotoes00491.png  Tomatoes

[70551 rows x 2 columns]

In [11]:
#Calculamos las cantidades de imagenes por fruta y sus porcentajes
df_raw["fruta"].value_counts() #Esto son los valores correctos

df_raw["percent"]=(df_raw.groupby("fruta")["fruta"].transform("size")/len(df_raw))*100

In [12]:
df_raw

                                     0     fruta    percent
0       Apple/Apple E/Apple E08152.png     Apple  15.855197
1         Apple/Apple E/Apple E117.png     Apple  15.855197
2         Apple/Apple E/Apple E103.png     Apple  15.855197
3      Apple/Apple E/Apple Ee01601.png     Apple  15.855197
4       Apple/Apple E/Apple E05112.png     Apple  15.855197
...                                ...       ...        ...
70546       Tomatoes/Tamotoes00485.png  Tomatoes   3.077207
70547      Tomatoes/Tamotoes001605.png  Tomatoes   3.077207
70548      Tomatoes/Tamotoes001611.png  Tomatoes   3.077207
70549      Tomatoes/Tamotoes001177.png  Tomatoes   3.077207
70550       Tomatoes/Tamotoes00491.png  Tomatoes   3.077207

[70551 rows x 3 columns]

In [13]:
df_raw.to_csv("raw_dataset.csv")